In [2]:
import pandas as pd
import pandera as pa    #utiliza esquemas para validar os dados

In [15]:
# sep=";" é usado pois os dados neste arquivo é separado por ';'
# parse_dates= usado para que a coluna que contém datas seja entendida como datas
# dayfirst=True para deixar aaaa-mm-dd
df = pd.read_csv("ocorrencia.csv", sep=";", encoding='latin1', parse_dates=['ocorrencia_dia'], dayfirst=True)
df.head(4)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,81027,81027,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2022-10-09,16:30:00,0
1,81030,81030,INCIDENTE,VITÓRIA,ES,SBVT,2022-10-09,16:20:00,0
2,81023,81023,INCIDENTE GRAVE,AMERICANA,SP,SDAI,2022-10-06,15:30:00,0
3,81029,81029,INCIDENTE,BELO HORIZONTE,MG,SBBH,2022-10-06,00:44:00,0

VALIDAÇÃO DOS DADOS

In [13]:
schema = pa.DataFrameSchema(
    columns={
        #required=False a coluna pode existir ou não
        #"codigo": pa.Column(pa.Int, required=False),
     
        "codigo_ocorrencia": pa.Column(pa.Int),
        "codigo_ocorrencia2":pa.Column(pa.Int),
        "ocorrencia_classificacao": pa.Column(pa.String),
        "ocorrencia_cidade": pa.Column(pa.String),
        
        #Check.str_lenghtExpressão que dá o tamanho minimo e máximo do dado que vem na coluna
        "ocorrencia_uf": pa.Column(pa.String, pa.Check.str_length(2,2)),
        "ocorrencia_aerodromo":	pa.Column(pa.String),
        "ocorrencia_dia": pa.Column(pa.DateTime),

        #Expressão regular para o formato 24hrs
        "ocorrencia_hora": pa.Column(pa.String, pa.Check.str_matches(r'^([0-1]?[0-9]|[2][0-3]):([0-5][0-9])(:[0-5][0-9])?$'), nullable=True), 
        "total_recomendacoes":pa.Column(pa.Int)
    }
)

In [16]:
schema.validate(df)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,81027,81027,INCIDENTE GRAVE,SÃO PAULO,SP,SBSP,2022-10-09,16:30:00,0
1,81030,81030,INCIDENTE,VITÓRIA,ES,SBVT,2022-10-09,16:20:00,0
2,81023,81023,INCIDENTE GRAVE,AMERICANA,SP,SDAI,2022-10-06,15:30:00,0
3,81029,81029,INCIDENTE,BELO HORIZONTE,MG,SBBH,2022-10-06,00:44:00,0
4,81025,81025,INCIDENTE,MANAUS,AM,SBEG,2022-10-05,20:56:00,0
...,...,...,...,...,...,...,...,...,...
6764,40324,40324,INCIDENTE,PELOTAS,RS,SBPK,2010-01-05,19:25:00,0
6765,39527,39527,ACIDENTE,LUCAS DO RIO VERDE,MT,***,2010-01-04,17:30:00,0
6766,40211,40211,INCIDENTE,RIO DE JANEIRO,RJ,***,2010-01-03,12:00:00,0
6767,40349,40349,INCIDENTE,BELÉM,PA,SBBE,2010-01-03,11:05:00,0
6768,40351,40351,INCIDENTE,RIO DE JANEIRO,RJ,SBRJ,2010-01-03,03:00:00,0

In [6]:
df.dtypes

codigo_ocorrencia                    int64
codigo_ocorrencia2                   int64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                  int64
dtype: object

0       10
1       10
2       10
3       10
4       10
        ..
6764     1
6765     1
6766     1
6767     1
6768     1
Name: ocorrencia_dia, Length: 6769, dtype: int64